import { Link } from "react-router";
import { Heart, Home, MapPin, PawPrint, Search, ShieldCheck, ArrowRight } from "lucide-react";

const actions = [
  { icon: Heart, title: "Adote um animal", text: "Navegue pelas publicações de animais disponíveis para adoção e encontre seu novo companheiro.", color: "text-accent bg-orange-50" },
  { icon: Search, title: "Encontre pets perdidos", text: "Divulgue seu animal perdido ou ajude a localizar pets da sua região que foram perdidos.", color: "text-rose-500 bg-rose-50" },
  { icon: Home, title: "Lar temporário", text: "Ofereça um lar temporário para animais que precisam de acolhimento enquanto encontram um dono.", color: "text-primary bg-secondary" },
];

export function LandingPage() {
 return <main className="min-h-screen bg-white text-foreground">
   <header className="px-5 md:px-8 py-4 border-b border-border flex items-center justify-between"><Link to="/" className="flex items-center gap-2 text-2xl font-black"><span className="w-12 h-12 rounded-xl bg-primary text-white grid place-items-center"><PawPrint size={25}/></span><span className="text-foreground">PET <span className="text-accent">AJUDA</span></span></Link><nav className="flex gap-3 items-center"><Link to="/entrar" className="font-bold px-4 py-2">Entrar</Link><Link to="/cadastro" className="bg-primary text-white px-5 py-2.5 rounded-xl font-bold shadow-sm">Cadastrar</Link></nav></header>
   <section className="max-w-7xl mx-auto px-5 md:px-8 py-16 md:py-24 grid lg:grid-cols-2 items-center gap-12">
    <div><div className="inline-flex gap-2 items-center bg-orange-50 text-accent px-4 py-2 rounded-full font-semibold text-sm"><MapPin size={16}/>Fortaleza — Ceará</div><h1 className="mt-8 text-5xl md:text-6xl leading-none font-black tracking-tight">Encontre seu novo<br/><span className="text-primary">melhor amigo</span></h1><p className="mt-7 max-w-xl text-xl leading-relaxed text-muted-foreground">Adote um animal, ajude a localizar pets perdidos ou ofereça um lar temporário. Juntos podemos mudar a vida de muitos animais em Fortaleza.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/cadastro" className="inline-flex items-center gap-3 bg-primary text-white font-bold px-7 py-4 rounded-xl shadow-sm">Cadastrar agora <ArrowRight size={20}/></Link><Link to="/entrar" className="bg-white border border-border font-bold px-7 py-4 rounded-xl shadow-sm">Já tenho conta</Link></div></div>
    <div className="relative min-h-96 rounded-3xl bg-gradient-to-br from-blue-100 via-orange-50 to-amber-100 overflow-hidden grid place-items-center"><div className="w-64 h-64 rounded-full bg-white/70 grid place-items-center shadow-inner"><PawPrint className="text-primary" size={130} strokeWidth={1.3}/></div><div className="absolute left-6 bottom-6 bg-white rounded-2xl p-5 shadow-lg flex items-center gap-4"><span className="w-12 h-12 rounded-full bg-green-100 text-green-600 grid place-items-center"><Heart size={25}/></span><span><b className="block">Adoção responsável</b><small className="text-muted-foreground">Mude uma vida hoje</small></span></div></div>
   </section>
   <section className="bg-slate-50 border-y border-border px-5 md:px-8 py-16"><div className="max-w-7xl mx-auto text-center"><h2 className="text-3xl font-black">Como funciona</h2><p className="text-muted-foreground mt-2 text-lg">Três formas de ajudar e ser ajudado</p><div className="grid md:grid-cols-3 gap-7 mt-10 text-left">{actions.map(({icon: Icon,title,text,color}) => <article key={title} className="bg-white rounded-2xl border border-border p-7 shadow-sm"><span className={`w-14 h-14 rounded-2xl grid place-items-center ${color}`}><Icon size={27}/></span><h3 className="font-black text-xl mt-6">{title}</h3><p className="mt-3 text-muted-foreground leading-relaxed">{text}</p></article>)}</div></div></section>
   <section className="max-w-4xl mx-auto text-center px-5 py-20"><span className="w-16 h-16 mx-auto bg-primary text-white rounded-2xl grid place-items-center"><ShieldCheck size={32}/></span><h2 className="text-3xl font-black mt-6">Projeto de extensão universitária</h2><p className="mt-4 text-lg text-muted-foreground">O PET AJUDA é uma plataforma sem fins lucrativos desenvolvida para conectar a comunidade de Fortaleza em prol da proteção animal.</p></section>
 </main>;
}
