import { useState } from "react";
import { Link, useNavigate } from "react-router";
import { PawPrint, X } from "lucide-react";
import { supabase } from "../../lib/supabase";

const terms = <>O PetAjuda é uma plataforma de extensão universitária sem fins lucrativos, desenvolvida para conectar a comunidade de Fortaleza em prol da proteção animal.<br/><br/>Ao utilizar esta plataforma, você concorda em:<br/><br/>(i) fornecer informações verídicas em seu cadastro e publicações;<br/><br/>(ii) utilizar os dados de contato divulgados nas publicações exclusivamente para fins relacionados à adoção, localização de animais perdidos ou oferta de lar temporário;<br/><br/>(iii) tratar todos os animais e usuários com respeito e responsabilidade.<br/><br/>O telefone informado em cada publicação será utilizado para contato direto via WhatsApp entre os usuários.<br/><br/>O PetAjuda não se responsabiliza por conversas ou acordos realizados fora da plataforma.<br/><br/>Publicações com conteúdo impróprio, fraudulento ou que violem os direitos dos animais poderão ser removidas.<br/><br/>O usuário somente poderá concluir o cadastro após aceitar os termos.</>;
export function SignupPage() {
 const [form,setForm]=useState({name:"",email:"",password:"",confirm:"",whatsapp:"",cpf:"",cep:""}); const [accepted,setAccepted]=useState(false); const [termsOpen,setTermsOpen]=useState(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const nav=useNavigate(); const change=(key:string,value:string)=>setForm({...form,[key]:value});
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(form.password!==form.confirm)return setMessage("As senhas não coincidem."); if(!accepted)return setMessage("Você precisa aceitar os Termos de Uso."); setBusy(true); const {data,error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{emailRedirectTo:`${window.location.origin}/feed`,data:{full_name:form.name,whatsapp:form.whatsapp,cpf:form.cpf,cep:form.cep}}}); setBusy(false); if(error)return setMessage(error.message); if(data.session) nav("/feed"); else setMessage("Conta criada! Confirme seu e-mail: ao clicar no link, você voltará automaticamente para o feed.");};
 const fields:[keyof typeof form,string,string][]=[["name","Nome completo","text"],["email","E-mail","email"],["password","Senha","password"],["confirm","Confirmar senha","password"],["whatsapp","WhatsApp","tel"],["cpf","CPF","text"],["cep","CEP","text"]];
 return <main className="min-h-screen bg-background grid place-items-center p-4"><form onSubmit={submit} className="w-full max-w-lg bg-white rounded-2xl border border-border shadow-sm p-7 flex flex-col gap-3"><div className="flex items-center gap-2 text-xl font-black"><span className="w-10 h-10 rounded-full bg-primary text-white grid place-items-center"><PawPrint size={21}/></span>PET <span className="text-accent -ml-2">AJUDA</span></div><h1 className="text-3xl font-black mt-2">Criar conta</h1>{fields.map(([key,label,type])=><label key={key} className="text-sm font-bold">{label}<input required type={type} value={form[key]} onChange={e=>change(key,e.target.value)} className="mt-1 w-full p-2.5 border border-border rounded-xl font-normal"/></label>)}<label className="flex gap-2 text-sm items-start mt-2"><input required checked={accepted} onChange={e=>setAccepted(e.target.checked)} type="checkbox" className="mt-1"/><span>Li e aceito os <button type="button" onClick={()=>setTermsOpen(true)} className="text-primary font-bold underline">Termos de Uso</button>.</span></label>{message&&<p className="text-sm text-red-600">{message}</p>}<button disabled={busy} className="bg-primary text-white font-bold py-3 rounded-xl">{busy?"Criando...":"Criar conta"}</button><p className="text-sm text-center">Já tem conta? <Link className="text-primary font-bold" to="/entrar">Entrar</Link></p></form>{termsOpen&&<div className="fixed inset-0 bg-slate-950/40 p-4 grid place-items-center"><section className="bg-white max-w-xl max-h-[85vh] overflow-auto rounded-2xl p-6 relative text-sm leading-relaxed"><button onClick={()=>setTermsOpen(false)} className="absolute right-4 top-4"><X/></button><h2 className="text-2xl font-black mb-4">Termos de Uso</h2><p>{terms}</p></section></div>}</main>;
}
